In [5]:
from bs4 import BeautifulSoup
import requests
import time
import smtplib
import datetime

In [39]:
headers = {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
    "Accept-Encoding": "gzip, deflate, br, zstd",
    "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
    "Priority": "u=0, i",
    "Sec-Ch-Ua": "\"Google Chrome\";v=\"147\", \"Not.A/Brand\";v=\"8\", \"Chromium\";v=\"147\"",
    "Sec-Ch-Ua-Mobile": "?0",
    "Sec-Ch-Ua-Platform": "\"Windows\"",
    "Sec-Fetch-Dest": "document",
    "Sec-Fetch-Mode": "navigate",
    "Sec-Fetch-Site": "cross-site",
    "Sec-Fetch-User": "?1",
    "Upgrade-Insecure-Requests": "1",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36",
}
url="https://www.amazon.in/FirseBUY-Data-Analyst-Sarcasm-Professional/dp/B0G5PP178J/ref=sr_1_3?crid=1WCW8L9C5V5YI&dib=eyJ2IjoiMSJ9.E5VGUuhh_znchCyTohVYB-nvvrwxJjuiZcnU7gjFIWrSlSqRYV0I4gtzTSverKsHEZM1_fmuV6I9u1Ua_ngn_C93Svsb6WYriRZpNFoq757gCYvjblJAyJApBqeA0kzy081RyUgH3S5SlJ00dTcSwGzppFdfX-MLX8EC7IAnAPOaJP_ZxNRZcA9JExoGfqw2inA6xQDUS92xAcaPlTnDZ8RsOzx7tn6KuH3qQkJh-9fLtVjnoo4pmaegHqgczmxmUG6dLrNkBEqfVPwcWsKqxi7so7s2SwxwxDgdR8jTSIU.MTMNlv1SEyJ-MqQL43ksrgXqebV1KKrWrqkDuZ2uvZI&dib_tag=se&keywords=data%2Banalyst%2Bshirt&qid=1788931467&sprefix=data%2Banalyst%2Btshirt%2Caps%2C244&sr=8-3&th=1"
response = requests.get(url,headers= headers)

In [40]:
data = response.text

In [41]:
soup = BeautifulSoup(data,"html")

In [42]:
price = soup.find(name="span",class_="a-price-whole").getText()

In [43]:
price

'363.'

In [44]:
price_clean= price.replace(".","")

In [45]:
price_clean_int= int(price_clean)

In [46]:
title=soup.find(name = "span",id="productTitle").getText()

In [47]:
title_clean = title.strip()

In [48]:
print(title_clean)
print(price_clean_int)

Data Analyst Funny Sarcasm Mug/Gift for Professional Job Title Gift Idea Ceramic Coffee Mug for Women and Men (11 Ounce), Black
363

In [60]:
import csv

In [ ]:
date = datetime.date.today()
print(date)

In [74]:
header = ['title','Price','Date']
data = [title_clean,price_clean_int,date]

In [88]:
# with open('amazon.csv','w',newline='',encoding='utf-8')as f :
#     writer = csv.writer(f)
#     writer.writerow(header)
#     writer.writerow(data)

In [76]:
import pandas as pd

In [82]:
df  = pd.read_csv("amazon.csv")

In [83]:
df

                                               title  Price        Date
0  Data Analyst Funny Sarcasm Mug/Gift for Profes...    363  2026-09-09
1  Data Analyst Funny Sarcasm Mug/Gift for Profes...    363  2026-09-09
2  Data Analyst Funny Sarcasm Mug/Gift for Profes...    363  2026-09-09
3  Data Analyst Funny Sarcasm Mug/Gift for Profes...    363  2026-09-09

In [81]:
with open('amazon.csv','a+',newline='',encoding='utf-8')as f :
    writer = csv.writer(f)
    writer.writerow(data)

In [90]:


def check_price():
    headers = {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
    "Accept-Encoding": "gzip, deflate, br, zstd",
    "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
    "Priority": "u=0, i",
    "Sec-Ch-Ua": "\"Google Chrome\";v=\"147\", \"Not.A/Brand\";v=\"8\", \"Chromium\";v=\"147\"",
    "Sec-Ch-Ua-Mobile": "?0",
    "Sec-Ch-Ua-Platform": "\"Windows\"",
    "Sec-Fetch-Dest": "document",
    "Sec-Fetch-Mode": "navigate",
    "Sec-Fetch-Site": "cross-site",
    "Sec-Fetch-User": "?1",
    "Upgrade-Insecure-Requests": "1",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36",
    }
    url="https://www.amazon.in/FirseBUY-Data-Analyst-Sarcasm-Professional/dp/B0G5PP178J/ref=sr_1_3?crid=1WCW8L9C5V5YI&dib=eyJ2IjoiMSJ9.E5VGUuhh_znchCyTohVYB-nvvrwxJjuiZcnU7gjFIWrSlSqRYV0I4gtzTSverKsHEZM1_fmuV6I9u1Ua_ngn_C93Svsb6WYriRZpNFoq757gCYvjblJAyJApBqeA0kzy081RyUgH3S5SlJ00dTcSwGzppFdfX-MLX8EC7IAnAPOaJP_ZxNRZcA9JExoGfqw2inA6xQDUS92xAcaPlTnDZ8RsOzx7tn6KuH3qQkJh-9fLtVjnoo4pmaegHqgczmxmUG6dLrNkBEqfVPwcWsKqxi7so7s2SwxwxDgdR8jTSIU.MTMNlv1SEyJ-MqQL43ksrgXqebV1KKrWrqkDuZ2uvZI&dib_tag=se&keywords=data%2Banalyst%2Bshirt&qid=1788931467&sprefix=data%2Banalyst%2Btshirt%2Caps%2C244&sr=8-3&th=1"
    response = requests.get(url,headers= headers)
    data = response.text
    soup = BeautifulSoup(data,"html")
    price = soup.find(name="span",class_="a-price-whole").getText()
    title=soup.find(name = "span",id="productTitle").getText()
    price_clean= price.replace(".","")
    price_clean_int= int(price_clean)
    title_clean = title.strip()
    import datetime
    date = datetime.date.today()
    import csv
    header = ['title','Price','Date']
    data = [title_clean,price_clean_int,date]
    with open('amazon.csv','a+',newline='',encoding='utf-8')as f :
        writer = csv.writer(f)
        writer.writerow(data)
    if price <500:
        send_mail()
def send_mail():
    message = f"{title_clean} is on sale {price_clean_int}"
    with smtplib.SMTP("smtp.gmail.com",port=587) as conn:
        conn.starttls()
        conn.login((os.environ["MY_EMAIL"]),(os.environ["PASSWORD"]))
        conn.sendmail(to_addrs=os.environ["MY_EMAIL"],
                      from_addr=os.environ["MY_EMAIL"],
                      msg=f"Subject:Amazon Price Alert!\n\n{message}\n{URL}".encode("utf-8"))

In [89]:
while(True):
    check_price()
    time.sleep(86400)

KeyboardInterrupt:

In [87]:
df  = pd.read_csv("amazon.csv")
df

                                               title  Price        Date
0  Data Analyst Funny Sarcasm Mug/Gift for Profes...    363  2026-09-09
1  Data Analyst Funny Sarcasm Mug/Gift for Profes...    363  2026-09-09
2  Data Analyst Funny Sarcasm Mug/Gift for Profes...    363  2026-09-09
3  Data Analyst Funny Sarcasm Mug/Gift for Profes...    363  2026-09-09
4  Data Analyst Funny Sarcasm Mug/Gift for Profes...    363  2026-09-09
5  Data Analyst Funny Sarcasm Mug/Gift for Profes...    363  2026-09-09
6  Data Analyst Funny Sarcasm Mug/Gift for Profes...    363  2026-09-09
7  Data Analyst Funny Sarcasm Mug/Gift for Profes...    363  2026-09-09